apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-planner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-planner
  template:
    metadata:
      labels:
        app: event-planner
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: event-planner:local
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: prod
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: storage
              mountPath: /app/storage
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: storage
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: event-planner
spec:
  selector:
    app: event-planner
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
